POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email": "test5@test.com",
    "password" : "12345678"
}

####
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
    "email": "test5@test.com",
    "password" : "12345678"
}
####
GET http://localhost:3000/auth/whoami
Content-Type: application/json
####
POST http://localhost:3000/auth/signout



###

GET http://localhost:3000/auth/6

###

GET http://localhost:3000/auth?email=assad3fas2@dsdf.com

### 

DELETE  http://localhost:3000/auth/3

### 

PATCH  http://localhost:3000/auth/5
Content-Type: application/json

{
    "email": "a@dAf.com",
    "password" : "AA"
}


